modLoader="javafml" #mandatory
loaderVersion="[28,)"
issueTrackerURL="https://github.com/sinkillerj/ProjectE/issues" #optional
displayURL="https://github.com/sinkillerj/ProjectE" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" #optional
# A text field displayed in the mod UI
# credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors="x3n0ph0b3, MidnightLightning, Magic Banana, MaPePeR, williewillus, Lilylicious" #optional

[[mods]]
modId="projecte"
version="2.0.0"
displayName="ProjectE"
updateJSONURL="https://raw.githubusercontent.com/sinkillerj/ProjectE/mc1.14.x/update.json"
description='''
A complete rewrite of EE2 for modern Minecraft versions.
'''
